const realestateapi = {
  input: {
    ids: [],
  },
  data: [
    {
      id: 175203,
      priorId: 1814285802,
      vacant: true,
      equity: 194668,
      ownerInfo: {
        ownerOccupied: true,
        absenteeOwner: false,
        instateAbsenteeOwner: false,
        outOfStateAbsenteeOwner: false,
        corporateOwned: false,
        ownershipLength: 6,
        owner1FirstName: 'BRIENNA',
        owner1LastName: 'BAILEY',
        owner1FullName: 'BRIENNA SHOWALTER BAILEY',
        owner2FirstName: 'NOEL',
        owner2LastName: 'NOEL',
        owner2FullName: 'NOEL',
        mailAddress: {
          fips: '41051',
          house: '3584',
          address: '3584 SE HOLGATE BLVD',
          street: 'HOLGATE',
          preDirection: 'SE',
          streetType: 'BLVD',
          city: 'PORTLAND',
          state: 'OR',
          zip: '97202',
          zip4: '3359',
          carrierRoute: 'C033',
          addressFormat: 'S',
          label: '3584 SE HOLGATE BLVD, PORTLAND, OR 97202',
        },
        equity: 194668,
      },
      propertyInfo: {
        address: {
          fips: '41051',
          house: '3584',
          address: '3584 SE HOLGATE BLVD',
          street: 'HOLGATE',
          preDirection: 'SE',
          streetType: 'BLVD',
          city: 'PORTLAND',
          state: 'OR',
          zip: '97202',
          zip4: '3359',
          carrierRoute: 'C033',
          congressionalDistrict: '329',
          label: '3584 SE HOLGATE BLVD, PORTLAND, OR 97202',
        },
        propertyType: 'SINGLE FAMILY RESIDENCE',
        latitude: 45.490113,
        longitude: -122.627015,
        stories: 2,
        roomsCount: 1,
        bedrooms: 3,
        bathrooms: 3,
        partialBathrooms: 0,
        parkingSpaces: 1,
        lotSquareFeet: 3392,
        buildingSquareFeet: 2953,
        livingSquareFeet: 2590,
        yearBuilt: 2017,
        fireplace: true,
        fireplaces: 1,
        garageType: '11',
        garageSquareFeet: 363,
        basementType: 'NO BASEMENT',
        basementSquareFeet: 0,
        basementSquareFeetFinished: 0,
        basementSquareFeetUnfinished: '0',
        heatingType: 'FORCED AIR',
        heatingFuelType: 'GAS',
        pool: false,
        garageSquareFeetFinished: null,
        garageSquareFeetUnfinished: null,
        basementSquareFeetUnFinished: null,
        basementFinishedPercent: null,
      },
      lotInfo: {
        legalDescription: 'HEARN, BLOCK 2, LOT 2',
        subdivision: 'HEARN',
        apn: '1S1E13AB 01700',
        apnUnformatted: '1S1E13AB01700',
        landUse: 'Residential',
        propertyClass:
          'The general use for the property is for residential purposes',
        propertyType: 'SINGLE FAMILY RESIDENCE',
        censusTract: '301',
        lotSquareFeet: 3392,
        'lot Acres': 0,
        lotNumber: '2',
        zoning: 'R5',
      },
      taxInfo: {
        propertyId: 175203,
        year: 2021,
        taxAmount: 863900,
        assessmentYear: 2021,
        assessedValue: 319520,
        assessedImprovementValue: '0',
        marketValue: 714400,
        marketImprovementValue: 487900,
        marketLandValue: 226500,
        'assessedLandValue ': 0,
      },
      demographics: {
        medianIncome: '130336',
        suggestedRent: '3010',
        fmrYear: '2023',
        fmrEfficiency: '1750',
        fmrOneBedroom: '1780',
        fmrTwoBedroom: '2020',
        fmrThreeBedroom: '2530',
        fmrFourBedroom: '3010',
        hudAreaName:
          'Washington-Arlington-Alexandria, DC-VA-MD HUD Metro FMR Area',
        hudAreaCode: 'METRO47900M47900',
      },
      currentMortgages: [
        {
          seq: '0',
          position: 'First',
          recordingDate: '2021-10-21T00:00:00.000Z',
          amount: 543932,
          interestRate: 0,
          documentDate: '2021-10-21T00:00:00.000Z',
          lenderName: 'CALIBER HOME LOANS INC',
          deedType: 'CONVENTIONAL',
        },
        {
          seq: '1',
          position: 'Second',
          amount: 0,
          interestRate: 0,
          lenderName: '',
          recordingDate: null,
          documentDate: null,
        },
      ],
      mortgageHistory: [
        {
          recordingDate: '2021-10-21T00:00:00.000Z',
          amount: 543932,
          interestRate: 0,
          documentDate: '2021-10-21T00:00:00.000Z',
          maturityDate: '2582409600000',
          lenderName: 'CALIBER HOME LOANS INC',
          term: '361',
          termType: 'MONTH',
          deedType: 'WARRANTY DEED',
          transactionType: 'TRANSFER',
          loanType: 'CONVENTIONAL',
          granteeName: 'BRIENNA SHOWALTER BAILEY, NOEL WHEAT KENDEL',
          seq: 0,
        },
        {
          recordingDate: '2017-06-09T00:00:00.000Z',
          amount: 389000,
          interestRate: 0,
          documentDate: '2017-06-09T00:00:00.000Z',
          maturityDate: '2443564800000',
          lenderName: "FIRST FIN'L BK&TR",
          term: '360',
          interestRateType: 'UNKNOWN',
          termType: 'MONTH',
          deedType: 'WARRANTY DEED',
          transactionType: 'SUBDIVISION RELATED TRANSFER',
          loanType: 'CONVENTIONAL',
          granteeName: 'DOUGLAS C MCCORD, TRACEY A MCCORD',
          seq: 1,
        },
      ],
      saleHistory: [
        {
          recordingDate: '2021-10-21T00:00:00.000Z',
          saleDate: '2021-10-21T00:00:00.000Z',
          saleAmount: 680000,
          documentType: 'DTWD',
          transactionType: '40',
          buyerNames: 'BRIENNA SHOWALTER BAILEY, NOEL WHEAT KENDEL',
          sellerNames: 'DOUGLAS C MCCORD, TRACEY A MCCORD',
          purchaseMethod: 'Financed',
          downPayment: 136068,
          ltv: 79.99,
          seq: 0,
        },
      ],
      foreclosureInfo: [],
    },
  ],
  statusCode: 200,
  statusMessage: 'Success',
  credits: 10,
};
